config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :drinks do
    collection do
      get 'search'
    end
    resources :reviews, except: [:index]
  end
  
  get '/users/five_star_drinks', to:'drinks#five_star_drinks'

  root 'drinks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  searchkick
    belongs_to :user
    has_many :reviews
    has_many :review_users, through: :reviews, source: :user
    
    has_attached_file :image, styles: { medium: "400x600#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :name, :ingredients, :taste, :bar_name, :bar_location, presence: true 
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :drink
validates :rating, numericality: {only_integer: true, less_than:6, greater_than:-1}
validates :comment, length: {maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :github, :google_oauth2]
  has_many :drinks
  has_many :reviews, dependent: :destroy
  has_many :drink_reviews, through: :drinks, source: :reviews
  has_many :reviewed_drinks, through: :reviews, source: :drink
  scope :five_star_drinks, -> {joins(drinks: [:reviews]).where("reviews.rating=5")}

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def search
    if params[:search].present?
      @drinks = Drink.search(params[:search])
    else
      @drinks = Drink.all
  end
end
  

  def five_star_drinks
    @users = User.five_star_drinks
    render 'users/index'
  end

  def index
    @drinks = Drink.all
  end

  def show
    @reviews = Review.where(drink_id: @drink.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @drink = current_user.drinks.build
  end


  def edit
  end

  def create
    @drink = current_user.drinks.build(drink_params)

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render :show, status: :created, location: @drink }
      else
        format.html { render :new }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @drink.update(drink_params)
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink }
      else
        format.html { render :edit }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @drink.destroy
    respond_to do |format|
      format.html { redirect_to drinks_url, notice: 'Drink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_drink
      @drink = Drink.find(params[:id])
    end

    def drink_params
      params.require(:drink).permit(:name, :ingredients, :taste, :bar_name, :bar_location, :bartender, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :get_drink
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  
  def index
    @reviews = Review.all
  end

  
  def show
  end

  
  def new
    @review = @drink.reviews.build
  end

  def edit
  end

  
  def create
    # review = Review.new(review_params)
    @review = @drink.reviews.build(review_params)
    @review.user_id = current_user.id
    # @review.drink_id = @drink_id
    respond_to do |format|
      if @review.save
        #redirect_to @drink
        format.html { redirect_to drink_path(@drink), notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        #render 'new'
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    drink = @review.drink
    @review.destroy
    respond_to do |format|
      format.html { redirect_to drink_url(drink), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def get_drink
    @drink = Drink.find(params[:drink_id])
  end
    
    def set_review
      @review = @drink.reviews.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    
    def facebook
        @user = User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
            set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
        else
            flash[:error] = "There was a problem signing in through Facebook"
            redirect_to new_user_registration_url
        end
    end

    def github
        @user = User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
            set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
        else
            flash[:error] = "There was a problem signing in through Github"
            redirect_to new_user_registration_url
        end
    end

    def google_oauth2
        @user = User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
            set_flash_message(:notice, :success, kind: "GoogleOauth2") if is_navigational_format?
        else
            flash[:error] = "There was a problem signing in through Google"
            redirect_to new_user_registration_url
        end
    end

    def failure
        flash[:error] = "There was a problem signing you in. Please register or try signing in later."
        redirect_to new_user_registration_url
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/drinks/_form.html.erb
<%= form_for @drink, html: { multipart: true } do |form| %>
  <% if drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
        <% drink.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_area :ingredients %>
  </div>

  <div class="field">
    <%= form.label :taste %>
    <%= form.text_field :taste %>
  </div>

  <div class="field">
    <%= form.label :bar_name %>
    <%= form.text_field :bar_name %>
  </div>

  <div class="field">
    <%= form.label :bar_location %>
    <%= form.text_area :bar_location %>
  </div>

  <div class="field">
    <%= form.label :bartender %>
    <%= form.text_field :bartender %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editing Drink</h1>

<%= render 'form', drink: @drink %>

<%= link_to 'Show', @drink %> |
<%= link_to 'Back', drinks_path %> |


 

app/views/drinks/index.html.erb
<% if !user_signed_in? %>
<div class="jumbotron">
<h1>Your Favorite Drinks Reviewed</h1>
<p>Track your favorite drinks with Mixster!</p>
<p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn  btn-primary btn-lg" %></p>
</div>

<%end%>

<div class="row"></div>
  <% @drinks.each do |drink| %>
    <div class="col-xs-6 col-md-3">
     <div class="thumbnail">
       <%= link_to (image_tag drink.image.url(:medium), class: 'image'), drink %>
      </div>
    </div>
  <%end%>

app/views/drinks/new.html.erb
<h1>New Drink</h1>

<%= render 'form', drink: @drink %>

<%= link_to 'Back', drinks_path %>

app/views/drinks/search.html.erb
<div class="row"></div>
  <% @drinks.each do |drink| %>
    <div class="col-xs-6 col-md-3">
     <div class="thumbnail">
       <%= link_to (image_tag drink.image.url(:medium), class: 'image'), drink %>
      </div>
    </div>
  <%end%>

app/views/drinks/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @drink.image.url(:medium) %>
         <div class="star-rating" data-source= <%= @avg_review %> ></div>
         <em><%= "#{@reviews.length} reviews"%> </em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
              <td><strong>Name:</strong></td>
              <td><%= @drink.name %></td>
              </tr>
              <tr>
              <td><strong>Ingredients:</strong></td>
              <td><%= @drink.ingredients %></td>
              </tr>
              <tr>
              <td><strong>Taste:</strong></td>
              <td><%= @drink.taste %></td>
              </tr>
              <tr>
              <td><strong>Bar name:</strong></td>
              <td><%= @drink.bar_name %></td>
              </tr>
              <tr>
              <td><strong>Bar location:</strong></td>
              <td><%= @drink.bar_location %></td>
              </tr>
              <tr>
              <td><strong>Bartender:</strong></td>
              <td><%= @drink.bartender %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write a Review",new_drink_review_path(@drink)%>
        </div>
      </div>
          <div class="col-md-7 col-md-offset-1 overlay-text">
          <h1 class="review_title"><%= @drink.name %></h1>
    
            <p><%=@drink_description%></p>

            <% if @reviews.blank? %>
            <h3>This drink has not been reviewed yet, Would you like to write the first review?</h3>
            <%= link_to "Write a review", new_drink_review_path(@drink), class: "btn btn-danger" %>
            <% else %>
            <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.rating %></p>
              <p><%= review.comment %></p>
              <%= link_to "show", drink_review_path(@drink, review) %>
          </div>
            <% end %>
            <% end %>
        </div>
        </div>
        </div>
        </div>


<%= link_to 'Edit', edit_drink_path(@drink) %> |
<%= link_to 'Back', drinks_path %> |
<%= link_to "Delete", @drink, method: "delete", data: { confirm: "Are you sure?", disable_with: "Processing..." } %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" </a>
      <%= link_to "Drink Reviews", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
      <li><%= link_to "New Drink", new_drink_path, class: "active" %></li>
      <li><%= link_to "5 Star Customers", users_five_star_drinks_path, class: "active" %></li>
      <li><%= link_to "Account", edit_user_registration_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
      <% end %>
          </ul>
        </li>
      </ul>
      <%= form_tag search_drinks_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MixsterApp</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container">
    <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-info") %>
  <% end %>
    <%= yield %>
  </div>
  
</body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model: [@drink, @review], local: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% @review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <br>

   <div class="field">
   <p style="color:blue;"</p> 
     <%= form.label :rating %>
     <%= form.number_field :rating %>
   </div>

   <! <div class="field">
   <div id="star-rating"></div>
   
   


  <div class="field">
  <p style="color:blue;"</p> 
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>
  
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
 $('#star-rating').raty({
   path: /assets/,
   scoreName: 'review[rating]'
 });
</script>

app/views/reviews/edit.html.erb
<h1 style="color:white;">Edit Review</h1>

<%= render 'form' %>

# <%= link_to 'Show', "#" %> |
<%= link_to 'Back', drink_path(@drink)  %>

app/views/reviews/index.html.erb
<h1>Listing Reviews </h1>

<table>
    <thead> 
        <tr>
            <th>Ratings</th>
            <th>Comments</th>
            <th colspan=3 ></th>
        </tr>
    </thead>

    <tbody>
        <% @reviews.each do |review| %>
        <tr>
            <td><%= review.rating %></td>
            <td><%= review.comment %></td>
            <td><%= link_to 'Show', review %></td>
            <td><%= link_to 'Edit', edit_review_path (review) %></td>
            <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?'  } %></td>
        </tr>
        end 
    </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1 style="color:white;">New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', drink_path(@drink) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<h1 style="color:blue;">Customer Review</h1>

<p>
  <p style="color:white;"</p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
<p style="color:white;"</p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p> 
<p style="color:white;"</p>
  <strong>User:</strong>
  <%= @review.user.email %>
 </p>

<%= link_to 'Back', drinks_path %> |

<%= link_to 'Edit', edit_drink_review_path(@review.drink, @review) %> |

<%= link_to "Delete", [@review.drink, @review], method: "delete", data: { confirm: "Are you sure?", disable_with: "Processing..." } %>

app/views/users/index.html.erb
<% if !user_signed_in? %>
<div class="jumbotron">
<h1>Your Favorite Drinks Reviewed</h1>
<p>Track your favorite drinks with Mixster!</p>
<p><%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn  btn-primary btn-lg" %></p>
</div>

<%end%>

<div class="row">
  <% @users.each do |user| %>
    <div class="col-xs-6 col-md-3">
    <%= user.email %>
    </div>
  <%end%>
  </div>